// Code generated by ent, DO NOT EDIT.

package shoppingcartitem

import (
	"healthyshopper/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldLTE(FieldID, id))
}

// ShoppingCartID applies equality check predicate on the "shopping_cart_id" field. It's identical to ShoppingCartIDEQ.
func ShoppingCartID(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldEQ(FieldShoppingCartID, v))
}

// ProductItemID applies equality check predicate on the "product_item_id" field. It's identical to ProductItemIDEQ.
func ProductItemID(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldEQ(FieldProductItemID, v))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldEQ(FieldQuantity, v))
}

// ShoppingCartIDEQ applies the EQ predicate on the "shopping_cart_id" field.
func ShoppingCartIDEQ(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldEQ(FieldShoppingCartID, v))
}

// ShoppingCartIDNEQ applies the NEQ predicate on the "shopping_cart_id" field.
func ShoppingCartIDNEQ(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldNEQ(FieldShoppingCartID, v))
}

// ShoppingCartIDIn applies the In predicate on the "shopping_cart_id" field.
func ShoppingCartIDIn(vs ...int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldIn(FieldShoppingCartID, vs...))
}

// ShoppingCartIDNotIn applies the NotIn predicate on the "shopping_cart_id" field.
func ShoppingCartIDNotIn(vs ...int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldNotIn(FieldShoppingCartID, vs...))
}

// ProductItemIDEQ applies the EQ predicate on the "product_item_id" field.
func ProductItemIDEQ(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldEQ(FieldProductItemID, v))
}

// ProductItemIDNEQ applies the NEQ predicate on the "product_item_id" field.
func ProductItemIDNEQ(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldNEQ(FieldProductItemID, v))
}

// ProductItemIDIn applies the In predicate on the "product_item_id" field.
func ProductItemIDIn(vs ...int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldIn(FieldProductItemID, vs...))
}

// ProductItemIDNotIn applies the NotIn predicate on the "product_item_id" field.
func ProductItemIDNotIn(vs ...int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldNotIn(FieldProductItemID, vs...))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(sql.FieldLTE(FieldQuantity, v))
}

// HasShoppingCart applies the HasEdge predicate on the "shopping_cart" edge.
func HasShoppingCart() predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ShoppingCartTable, ShoppingCartColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShoppingCartWith applies the HasEdge predicate on the "shopping_cart" edge with a given conditions (other predicates).
func HasShoppingCartWith(preds ...predicate.ShoppingCart) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(func(s *sql.Selector) {
		step := newShoppingCartStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasProductItem applies the HasEdge predicate on the "product_item" edge.
func HasProductItem() predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProductItemTable, ProductItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProductItemWith applies the HasEdge predicate on the "product_item" edge with a given conditions (other predicates).
func HasProductItemWith(preds ...predicate.ProductItem) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(func(s *sql.Selector) {
		step := newProductItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ShoppingCartItem) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ShoppingCartItem) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ShoppingCartItem) predicate.ShoppingCartItem {
	return predicate.ShoppingCartItem(func(s *sql.Selector) {
		p(s.Not())
	})
}
