// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"healthyshopper/ent/ingredientstable"
	"healthyshopper/ent/predicate"
	"healthyshopper/ent/product"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IngredientsTableQuery is the builder for querying IngredientsTable entities.
type IngredientsTableQuery struct {
	config
	ctx              *QueryContext
	order            []ingredientstable.OrderOption
	inters           []Interceptor
	predicates       []predicate.IngredientsTable
	withProduct      *ProductQuery
	modifiers        []func(*sql.Selector)
	loadTotal        []func(context.Context, []*IngredientsTable) error
	withNamedProduct map[string]*ProductQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IngredientsTableQuery builder.
func (itq *IngredientsTableQuery) Where(ps ...predicate.IngredientsTable) *IngredientsTableQuery {
	itq.predicates = append(itq.predicates, ps...)
	return itq
}

// Limit the number of records to be returned by this query.
func (itq *IngredientsTableQuery) Limit(limit int) *IngredientsTableQuery {
	itq.ctx.Limit = &limit
	return itq
}

// Offset to start from.
func (itq *IngredientsTableQuery) Offset(offset int) *IngredientsTableQuery {
	itq.ctx.Offset = &offset
	return itq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (itq *IngredientsTableQuery) Unique(unique bool) *IngredientsTableQuery {
	itq.ctx.Unique = &unique
	return itq
}

// Order specifies how the records should be ordered.
func (itq *IngredientsTableQuery) Order(o ...ingredientstable.OrderOption) *IngredientsTableQuery {
	itq.order = append(itq.order, o...)
	return itq
}

// QueryProduct chains the current query on the "product" edge.
func (itq *IngredientsTableQuery) QueryProduct() *ProductQuery {
	query := (&ProductClient{config: itq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := itq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := itq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(ingredientstable.Table, ingredientstable.FieldID, selector),
			sqlgraph.To(product.Table, product.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ingredientstable.ProductTable, ingredientstable.ProductColumn),
		)
		fromU = sqlgraph.SetNeighbors(itq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first IngredientsTable entity from the query.
// Returns a *NotFoundError when no IngredientsTable was found.
func (itq *IngredientsTableQuery) First(ctx context.Context) (*IngredientsTable, error) {
	nodes, err := itq.Limit(1).All(setContextOp(ctx, itq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ingredientstable.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (itq *IngredientsTableQuery) FirstX(ctx context.Context) *IngredientsTable {
	node, err := itq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IngredientsTable ID from the query.
// Returns a *NotFoundError when no IngredientsTable ID was found.
func (itq *IngredientsTableQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = itq.Limit(1).IDs(setContextOp(ctx, itq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ingredientstable.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (itq *IngredientsTableQuery) FirstIDX(ctx context.Context) int {
	id, err := itq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IngredientsTable entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IngredientsTable entity is found.
// Returns a *NotFoundError when no IngredientsTable entities are found.
func (itq *IngredientsTableQuery) Only(ctx context.Context) (*IngredientsTable, error) {
	nodes, err := itq.Limit(2).All(setContextOp(ctx, itq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ingredientstable.Label}
	default:
		return nil, &NotSingularError{ingredientstable.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (itq *IngredientsTableQuery) OnlyX(ctx context.Context) *IngredientsTable {
	node, err := itq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IngredientsTable ID in the query.
// Returns a *NotSingularError when more than one IngredientsTable ID is found.
// Returns a *NotFoundError when no entities are found.
func (itq *IngredientsTableQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = itq.Limit(2).IDs(setContextOp(ctx, itq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ingredientstable.Label}
	default:
		err = &NotSingularError{ingredientstable.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (itq *IngredientsTableQuery) OnlyIDX(ctx context.Context) int {
	id, err := itq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IngredientsTables.
func (itq *IngredientsTableQuery) All(ctx context.Context) ([]*IngredientsTable, error) {
	ctx = setContextOp(ctx, itq.ctx, "All")
	if err := itq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IngredientsTable, *IngredientsTableQuery]()
	return withInterceptors[[]*IngredientsTable](ctx, itq, qr, itq.inters)
}

// AllX is like All, but panics if an error occurs.
func (itq *IngredientsTableQuery) AllX(ctx context.Context) []*IngredientsTable {
	nodes, err := itq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IngredientsTable IDs.
func (itq *IngredientsTableQuery) IDs(ctx context.Context) (ids []int, err error) {
	if itq.ctx.Unique == nil && itq.path != nil {
		itq.Unique(true)
	}
	ctx = setContextOp(ctx, itq.ctx, "IDs")
	if err = itq.Select(ingredientstable.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (itq *IngredientsTableQuery) IDsX(ctx context.Context) []int {
	ids, err := itq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (itq *IngredientsTableQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, itq.ctx, "Count")
	if err := itq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, itq, querierCount[*IngredientsTableQuery](), itq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (itq *IngredientsTableQuery) CountX(ctx context.Context) int {
	count, err := itq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (itq *IngredientsTableQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, itq.ctx, "Exist")
	switch _, err := itq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (itq *IngredientsTableQuery) ExistX(ctx context.Context) bool {
	exist, err := itq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IngredientsTableQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (itq *IngredientsTableQuery) Clone() *IngredientsTableQuery {
	if itq == nil {
		return nil
	}
	return &IngredientsTableQuery{
		config:      itq.config,
		ctx:         itq.ctx.Clone(),
		order:       append([]ingredientstable.OrderOption{}, itq.order...),
		inters:      append([]Interceptor{}, itq.inters...),
		predicates:  append([]predicate.IngredientsTable{}, itq.predicates...),
		withProduct: itq.withProduct.Clone(),
		// clone intermediate query.
		sql:  itq.sql.Clone(),
		path: itq.path,
	}
}

// WithProduct tells the query-builder to eager-load the nodes that are connected to
// the "product" edge. The optional arguments are used to configure the query builder of the edge.
func (itq *IngredientsTableQuery) WithProduct(opts ...func(*ProductQuery)) *IngredientsTableQuery {
	query := (&ProductClient{config: itq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	itq.withProduct = query
	return itq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IngredientsTable.Query().
//		GroupBy(ingredientstable.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (itq *IngredientsTableQuery) GroupBy(field string, fields ...string) *IngredientsTableGroupBy {
	itq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IngredientsTableGroupBy{build: itq}
	grbuild.flds = &itq.ctx.Fields
	grbuild.label = ingredientstable.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.IngredientsTable.Query().
//		Select(ingredientstable.FieldName).
//		Scan(ctx, &v)
func (itq *IngredientsTableQuery) Select(fields ...string) *IngredientsTableSelect {
	itq.ctx.Fields = append(itq.ctx.Fields, fields...)
	sbuild := &IngredientsTableSelect{IngredientsTableQuery: itq}
	sbuild.label = ingredientstable.Label
	sbuild.flds, sbuild.scan = &itq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IngredientsTableSelect configured with the given aggregations.
func (itq *IngredientsTableQuery) Aggregate(fns ...AggregateFunc) *IngredientsTableSelect {
	return itq.Select().Aggregate(fns...)
}

func (itq *IngredientsTableQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range itq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, itq); err != nil {
				return err
			}
		}
	}
	for _, f := range itq.ctx.Fields {
		if !ingredientstable.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if itq.path != nil {
		prev, err := itq.path(ctx)
		if err != nil {
			return err
		}
		itq.sql = prev
	}
	return nil
}

func (itq *IngredientsTableQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IngredientsTable, error) {
	var (
		nodes       = []*IngredientsTable{}
		_spec       = itq.querySpec()
		loadedTypes = [1]bool{
			itq.withProduct != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IngredientsTable).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IngredientsTable{config: itq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(itq.modifiers) > 0 {
		_spec.Modifiers = itq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, itq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := itq.withProduct; query != nil {
		if err := itq.loadProduct(ctx, query, nodes,
			func(n *IngredientsTable) { n.Edges.Product = []*Product{} },
			func(n *IngredientsTable, e *Product) { n.Edges.Product = append(n.Edges.Product, e) }); err != nil {
			return nil, err
		}
	}
	for name, query := range itq.withNamedProduct {
		if err := itq.loadProduct(ctx, query, nodes,
			func(n *IngredientsTable) { n.appendNamedProduct(name) },
			func(n *IngredientsTable, e *Product) { n.appendNamedProduct(name, e) }); err != nil {
			return nil, err
		}
	}
	for i := range itq.loadTotal {
		if err := itq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (itq *IngredientsTableQuery) loadProduct(ctx context.Context, query *ProductQuery, nodes []*IngredientsTable, init func(*IngredientsTable), assign func(*IngredientsTable, *Product)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*IngredientsTable)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(product.FieldIngredientsTableID)
	}
	query.Where(predicate.Product(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(ingredientstable.ProductColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.IngredientsTableID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "ingredients_table_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (itq *IngredientsTableQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := itq.querySpec()
	if len(itq.modifiers) > 0 {
		_spec.Modifiers = itq.modifiers
	}
	_spec.Node.Columns = itq.ctx.Fields
	if len(itq.ctx.Fields) > 0 {
		_spec.Unique = itq.ctx.Unique != nil && *itq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, itq.driver, _spec)
}

func (itq *IngredientsTableQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ingredientstable.Table, ingredientstable.Columns, sqlgraph.NewFieldSpec(ingredientstable.FieldID, field.TypeInt))
	_spec.From = itq.sql
	if unique := itq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if itq.path != nil {
		_spec.Unique = true
	}
	if fields := itq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ingredientstable.FieldID)
		for i := range fields {
			if fields[i] != ingredientstable.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := itq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := itq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := itq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := itq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (itq *IngredientsTableQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(itq.driver.Dialect())
	t1 := builder.Table(ingredientstable.Table)
	columns := itq.ctx.Fields
	if len(columns) == 0 {
		columns = ingredientstable.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if itq.sql != nil {
		selector = itq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if itq.ctx.Unique != nil && *itq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range itq.predicates {
		p(selector)
	}
	for _, p := range itq.order {
		p(selector)
	}
	if offset := itq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := itq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WithNamedProduct tells the query-builder to eager-load the nodes that are connected to the "product"
// edge with the given name. The optional arguments are used to configure the query builder of the edge.
func (itq *IngredientsTableQuery) WithNamedProduct(name string, opts ...func(*ProductQuery)) *IngredientsTableQuery {
	query := (&ProductClient{config: itq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	if itq.withNamedProduct == nil {
		itq.withNamedProduct = make(map[string]*ProductQuery)
	}
	itq.withNamedProduct[name] = query
	return itq
}

// IngredientsTableGroupBy is the group-by builder for IngredientsTable entities.
type IngredientsTableGroupBy struct {
	selector
	build *IngredientsTableQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (itgb *IngredientsTableGroupBy) Aggregate(fns ...AggregateFunc) *IngredientsTableGroupBy {
	itgb.fns = append(itgb.fns, fns...)
	return itgb
}

// Scan applies the selector query and scans the result into the given value.
func (itgb *IngredientsTableGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, itgb.build.ctx, "GroupBy")
	if err := itgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IngredientsTableQuery, *IngredientsTableGroupBy](ctx, itgb.build, itgb, itgb.build.inters, v)
}

func (itgb *IngredientsTableGroupBy) sqlScan(ctx context.Context, root *IngredientsTableQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(itgb.fns))
	for _, fn := range itgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*itgb.flds)+len(itgb.fns))
		for _, f := range *itgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*itgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := itgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IngredientsTableSelect is the builder for selecting fields of IngredientsTable entities.
type IngredientsTableSelect struct {
	*IngredientsTableQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (its *IngredientsTableSelect) Aggregate(fns ...AggregateFunc) *IngredientsTableSelect {
	its.fns = append(its.fns, fns...)
	return its
}

// Scan applies the selector query and scans the result into the given value.
func (its *IngredientsTableSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, its.ctx, "Select")
	if err := its.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IngredientsTableQuery, *IngredientsTableSelect](ctx, its.IngredientsTableQuery, its, its.inters, v)
}

func (its *IngredientsTableSelect) sqlScan(ctx context.Context, root *IngredientsTableQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(its.fns))
	for _, fn := range its.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*its.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := its.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
