// Code generated by ent, DO NOT EDIT.

package ent

import (
	"healthyshopper/ent/address"
	"healthyshopper/ent/product"
	"healthyshopper/ent/schema"
	"healthyshopper/ent/shoppingcartitem"
	"healthyshopper/ent/user"
	"healthyshopper/ent/useraddress"
	"healthyshopper/ent/userreview"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	addressFields := schema.Address{}.Fields()
	_ = addressFields
	// addressDescPhoneNumber is the schema descriptor for phone_number field.
	addressDescPhoneNumber := addressFields[0].Descriptor()
	// address.PhoneNumberValidator is a validator for the "phone_number" field. It is called by the builders before save.
	address.PhoneNumberValidator = func() func(string) error {
		validators := addressDescPhoneNumber.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(phone_number string) error {
			for _, fn := range fns {
				if err := fn(phone_number); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// addressDescAddressLine1 is the schema descriptor for address_line1 field.
	addressDescAddressLine1 := addressFields[1].Descriptor()
	// address.AddressLine1Validator is a validator for the "address_line1" field. It is called by the builders before save.
	address.AddressLine1Validator = func() func(string) error {
		validators := addressDescAddressLine1.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(address_line1 string) error {
			for _, fn := range fns {
				if err := fn(address_line1); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// addressDescAddressLine2 is the schema descriptor for address_line2 field.
	addressDescAddressLine2 := addressFields[2].Descriptor()
	// address.AddressLine2Validator is a validator for the "address_line2" field. It is called by the builders before save.
	address.AddressLine2Validator = addressDescAddressLine2.Validators[0].(func(string) error)
	// addressDescCity is the schema descriptor for city field.
	addressDescCity := addressFields[3].Descriptor()
	// address.CityValidator is a validator for the "city" field. It is called by the builders before save.
	address.CityValidator = func() func(string) error {
		validators := addressDescCity.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(city string) error {
			for _, fn := range fns {
				if err := fn(city); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// addressDescState is the schema descriptor for state field.
	addressDescState := addressFields[4].Descriptor()
	// address.StateValidator is a validator for the "state" field. It is called by the builders before save.
	address.StateValidator = func() func(string) error {
		validators := addressDescState.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(state string) error {
			for _, fn := range fns {
				if err := fn(state); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// addressDescCountry is the schema descriptor for country field.
	addressDescCountry := addressFields[5].Descriptor()
	// address.CountryValidator is a validator for the "country" field. It is called by the builders before save.
	address.CountryValidator = func() func(string) error {
		validators := addressDescCountry.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(country string) error {
			for _, fn := range fns {
				if err := fn(country); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// addressDescPostalCode is the schema descriptor for postal_code field.
	addressDescPostalCode := addressFields[6].Descriptor()
	// address.PostalCodeValidator is a validator for the "postal_code" field. It is called by the builders before save.
	address.PostalCodeValidator = func() func(string) error {
		validators := addressDescPostalCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(postal_code string) error {
			for _, fn := range fns {
				if err := fn(postal_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	productFields := schema.Product{}.Fields()
	_ = productFields
	// productDescName is the schema descriptor for name field.
	productDescName := productFields[0].Descriptor()
	// product.NameValidator is a validator for the "name" field. It is called by the builders before save.
	product.NameValidator = func() func(string) error {
		validators := productDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// productDescDescription is the schema descriptor for description field.
	productDescDescription := productFields[1].Descriptor()
	// product.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	product.DescriptionValidator = func() func(string) error {
		validators := productDescDescription.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(description string) error {
			for _, fn := range fns {
				if err := fn(description); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// productDescProductImage is the schema descriptor for product_image field.
	productDescProductImage := productFields[2].Descriptor()
	// product.ProductImageValidator is a validator for the "product_image" field. It is called by the builders before save.
	product.ProductImageValidator = func() func(string) error {
		validators := productDescProductImage.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(product_image string) error {
			for _, fn := range fns {
				if err := fn(product_image); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// productDescProductCategoryID is the schema descriptor for product_category_id field.
	productDescProductCategoryID := productFields[3].Descriptor()
	// product.ProductCategoryIDValidator is a validator for the "product_category_id" field. It is called by the builders before save.
	product.ProductCategoryIDValidator = productDescProductCategoryID.Validators[0].(func(int) error)
	// productDescIngredientsListID is the schema descriptor for ingredients_list_id field.
	productDescIngredientsListID := productFields[4].Descriptor()
	// product.IngredientsListIDValidator is a validator for the "ingredients_list_id" field. It is called by the builders before save.
	product.IngredientsListIDValidator = productDescIngredientsListID.Validators[0].(func(int) error)
	// productDescNutritionalInformationID is the schema descriptor for nutritional_information_id field.
	productDescNutritionalInformationID := productFields[5].Descriptor()
	// product.NutritionalInformationIDValidator is a validator for the "nutritional_information_id" field. It is called by the builders before save.
	product.NutritionalInformationIDValidator = productDescNutritionalInformationID.Validators[0].(func(int) error)
	// productDescPromotionID is the schema descriptor for promotion_id field.
	productDescPromotionID := productFields[6].Descriptor()
	// product.PromotionIDValidator is a validator for the "promotion_id" field. It is called by the builders before save.
	product.PromotionIDValidator = productDescPromotionID.Validators[0].(func(int) error)
	// productDescCreatedAt is the schema descriptor for created_at field.
	productDescCreatedAt := productFields[7].Descriptor()
	// product.DefaultCreatedAt holds the default value on creation for the created_at field.
	product.DefaultCreatedAt = productDescCreatedAt.Default.(func() time.Time)
	shoppingcartitemFields := schema.ShoppingCartItem{}.Fields()
	_ = shoppingcartitemFields
	// shoppingcartitemDescQuantity is the schema descriptor for quantity field.
	shoppingcartitemDescQuantity := shoppingcartitemFields[2].Descriptor()
	// shoppingcartitem.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	shoppingcartitem.QuantityValidator = shoppingcartitemDescQuantity.Validators[0].(func(int) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescEmailAddress is the schema descriptor for email_address field.
	userDescEmailAddress := userFields[1].Descriptor()
	// user.EmailAddressValidator is a validator for the "email_address" field. It is called by the builders before save.
	user.EmailAddressValidator = func() func(string) error {
		validators := userDescEmailAddress.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email_address string) error {
			for _, fn := range fns {
				if err := fn(email_address); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[2].Descriptor()
	// user.PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	user.PasswordValidator = func() func(string) error {
		validators := userDescPassword.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(password string) error {
			for _, fn := range fns {
				if err := fn(password); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[3].Descriptor()
	// user.FirstNameValidator is a validator for the "first_name" field. It is called by the builders before save.
	user.FirstNameValidator = func() func(string) error {
		validators := userDescFirstName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(first_name string) error {
			for _, fn := range fns {
				if err := fn(first_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[4].Descriptor()
	// user.LastNameValidator is a validator for the "last_name" field. It is called by the builders before save.
	user.LastNameValidator = func() func(string) error {
		validators := userDescLastName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(last_name string) error {
			for _, fn := range fns {
				if err := fn(last_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[6].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	useraddressFields := schema.UserAddress{}.Fields()
	_ = useraddressFields
	// useraddressDescIsDefault is the schema descriptor for is_default field.
	useraddressDescIsDefault := useraddressFields[2].Descriptor()
	// useraddress.DefaultIsDefault holds the default value on creation for the is_default field.
	useraddress.DefaultIsDefault = useraddressDescIsDefault.Default.(bool)
	userreviewFields := schema.UserReview{}.Fields()
	_ = userreviewFields
	// userreviewDescRating is the schema descriptor for rating field.
	userreviewDescRating := userreviewFields[2].Descriptor()
	// userreview.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	userreview.RatingValidator = userreviewDescRating.Validators[0].(func(int) error)
	// userreviewDescReview is the schema descriptor for review field.
	userreviewDescReview := userreviewFields[3].Descriptor()
	// userreview.ReviewValidator is a validator for the "review" field. It is called by the builders before save.
	userreview.ReviewValidator = func() func(string) error {
		validators := userreviewDescReview.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(review string) error {
			for _, fn := range fns {
				if err := fn(review); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userreviewDescCreatedAt is the schema descriptor for created_at field.
	userreviewDescCreatedAt := userreviewFields[4].Descriptor()
	// userreview.DefaultCreatedAt holds the default value on creation for the created_at field.
	userreview.DefaultCreatedAt = userreviewDescCreatedAt.Default.(func() time.Time)
	// userreviewDescUpdatedAt is the schema descriptor for updated_at field.
	userreviewDescUpdatedAt := userreviewFields[5].Descriptor()
	// userreview.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userreview.DefaultUpdatedAt = userreviewDescUpdatedAt.Default.(func() time.Time)
	// userreview.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userreview.UpdateDefaultUpdatedAt = userreviewDescUpdatedAt.UpdateDefault.(func() time.Time)
}
