// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"healthyshopper/ent/predicate"
	"healthyshopper/ent/shippingaddress"
	"healthyshopper/ent/shoporder"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShopOrderQuery is the builder for querying ShopOrder entities.
type ShopOrderQuery struct {
	config
	ctx                 *QueryContext
	order               []shoporder.OrderOption
	inters              []Interceptor
	predicates          []predicate.ShopOrder
	withShippingAddress *ShippingAddressQuery
	modifiers           []func(*sql.Selector)
	loadTotal           []func(context.Context, []*ShopOrder) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ShopOrderQuery builder.
func (soq *ShopOrderQuery) Where(ps ...predicate.ShopOrder) *ShopOrderQuery {
	soq.predicates = append(soq.predicates, ps...)
	return soq
}

// Limit the number of records to be returned by this query.
func (soq *ShopOrderQuery) Limit(limit int) *ShopOrderQuery {
	soq.ctx.Limit = &limit
	return soq
}

// Offset to start from.
func (soq *ShopOrderQuery) Offset(offset int) *ShopOrderQuery {
	soq.ctx.Offset = &offset
	return soq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (soq *ShopOrderQuery) Unique(unique bool) *ShopOrderQuery {
	soq.ctx.Unique = &unique
	return soq
}

// Order specifies how the records should be ordered.
func (soq *ShopOrderQuery) Order(o ...shoporder.OrderOption) *ShopOrderQuery {
	soq.order = append(soq.order, o...)
	return soq
}

// QueryShippingAddress chains the current query on the "shipping_address" edge.
func (soq *ShopOrderQuery) QueryShippingAddress() *ShippingAddressQuery {
	query := (&ShippingAddressClient{config: soq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := soq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := soq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(shoporder.Table, shoporder.FieldID, selector),
			sqlgraph.To(shippingaddress.Table, shippingaddress.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, shoporder.ShippingAddressTable, shoporder.ShippingAddressColumn),
		)
		fromU = sqlgraph.SetNeighbors(soq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ShopOrder entity from the query.
// Returns a *NotFoundError when no ShopOrder was found.
func (soq *ShopOrderQuery) First(ctx context.Context) (*ShopOrder, error) {
	nodes, err := soq.Limit(1).All(setContextOp(ctx, soq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{shoporder.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (soq *ShopOrderQuery) FirstX(ctx context.Context) *ShopOrder {
	node, err := soq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ShopOrder ID from the query.
// Returns a *NotFoundError when no ShopOrder ID was found.
func (soq *ShopOrderQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = soq.Limit(1).IDs(setContextOp(ctx, soq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{shoporder.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (soq *ShopOrderQuery) FirstIDX(ctx context.Context) int {
	id, err := soq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ShopOrder entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ShopOrder entity is found.
// Returns a *NotFoundError when no ShopOrder entities are found.
func (soq *ShopOrderQuery) Only(ctx context.Context) (*ShopOrder, error) {
	nodes, err := soq.Limit(2).All(setContextOp(ctx, soq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{shoporder.Label}
	default:
		return nil, &NotSingularError{shoporder.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (soq *ShopOrderQuery) OnlyX(ctx context.Context) *ShopOrder {
	node, err := soq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ShopOrder ID in the query.
// Returns a *NotSingularError when more than one ShopOrder ID is found.
// Returns a *NotFoundError when no entities are found.
func (soq *ShopOrderQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = soq.Limit(2).IDs(setContextOp(ctx, soq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{shoporder.Label}
	default:
		err = &NotSingularError{shoporder.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (soq *ShopOrderQuery) OnlyIDX(ctx context.Context) int {
	id, err := soq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ShopOrders.
func (soq *ShopOrderQuery) All(ctx context.Context) ([]*ShopOrder, error) {
	ctx = setContextOp(ctx, soq.ctx, "All")
	if err := soq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ShopOrder, *ShopOrderQuery]()
	return withInterceptors[[]*ShopOrder](ctx, soq, qr, soq.inters)
}

// AllX is like All, but panics if an error occurs.
func (soq *ShopOrderQuery) AllX(ctx context.Context) []*ShopOrder {
	nodes, err := soq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ShopOrder IDs.
func (soq *ShopOrderQuery) IDs(ctx context.Context) (ids []int, err error) {
	if soq.ctx.Unique == nil && soq.path != nil {
		soq.Unique(true)
	}
	ctx = setContextOp(ctx, soq.ctx, "IDs")
	if err = soq.Select(shoporder.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (soq *ShopOrderQuery) IDsX(ctx context.Context) []int {
	ids, err := soq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (soq *ShopOrderQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, soq.ctx, "Count")
	if err := soq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, soq, querierCount[*ShopOrderQuery](), soq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (soq *ShopOrderQuery) CountX(ctx context.Context) int {
	count, err := soq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (soq *ShopOrderQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, soq.ctx, "Exist")
	switch _, err := soq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (soq *ShopOrderQuery) ExistX(ctx context.Context) bool {
	exist, err := soq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ShopOrderQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (soq *ShopOrderQuery) Clone() *ShopOrderQuery {
	if soq == nil {
		return nil
	}
	return &ShopOrderQuery{
		config:              soq.config,
		ctx:                 soq.ctx.Clone(),
		order:               append([]shoporder.OrderOption{}, soq.order...),
		inters:              append([]Interceptor{}, soq.inters...),
		predicates:          append([]predicate.ShopOrder{}, soq.predicates...),
		withShippingAddress: soq.withShippingAddress.Clone(),
		// clone intermediate query.
		sql:  soq.sql.Clone(),
		path: soq.path,
	}
}

// WithShippingAddress tells the query-builder to eager-load the nodes that are connected to
// the "shipping_address" edge. The optional arguments are used to configure the query builder of the edge.
func (soq *ShopOrderQuery) WithShippingAddress(opts ...func(*ShippingAddressQuery)) *ShopOrderQuery {
	query := (&ShippingAddressClient{config: soq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	soq.withShippingAddress = query
	return soq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OrderDateAndTime time.Time `json:"order_date_and_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ShopOrder.Query().
//		GroupBy(shoporder.FieldOrderDateAndTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (soq *ShopOrderQuery) GroupBy(field string, fields ...string) *ShopOrderGroupBy {
	soq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ShopOrderGroupBy{build: soq}
	grbuild.flds = &soq.ctx.Fields
	grbuild.label = shoporder.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OrderDateAndTime time.Time `json:"order_date_and_time,omitempty"`
//	}
//
//	client.ShopOrder.Query().
//		Select(shoporder.FieldOrderDateAndTime).
//		Scan(ctx, &v)
func (soq *ShopOrderQuery) Select(fields ...string) *ShopOrderSelect {
	soq.ctx.Fields = append(soq.ctx.Fields, fields...)
	sbuild := &ShopOrderSelect{ShopOrderQuery: soq}
	sbuild.label = shoporder.Label
	sbuild.flds, sbuild.scan = &soq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ShopOrderSelect configured with the given aggregations.
func (soq *ShopOrderQuery) Aggregate(fns ...AggregateFunc) *ShopOrderSelect {
	return soq.Select().Aggregate(fns...)
}

func (soq *ShopOrderQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range soq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, soq); err != nil {
				return err
			}
		}
	}
	for _, f := range soq.ctx.Fields {
		if !shoporder.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if soq.path != nil {
		prev, err := soq.path(ctx)
		if err != nil {
			return err
		}
		soq.sql = prev
	}
	return nil
}

func (soq *ShopOrderQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ShopOrder, error) {
	var (
		nodes       = []*ShopOrder{}
		_spec       = soq.querySpec()
		loadedTypes = [1]bool{
			soq.withShippingAddress != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ShopOrder).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ShopOrder{config: soq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(soq.modifiers) > 0 {
		_spec.Modifiers = soq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, soq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := soq.withShippingAddress; query != nil {
		if err := soq.loadShippingAddress(ctx, query, nodes, nil,
			func(n *ShopOrder, e *ShippingAddress) { n.Edges.ShippingAddress = e }); err != nil {
			return nil, err
		}
	}
	for i := range soq.loadTotal {
		if err := soq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (soq *ShopOrderQuery) loadShippingAddress(ctx context.Context, query *ShippingAddressQuery, nodes []*ShopOrder, init func(*ShopOrder), assign func(*ShopOrder, *ShippingAddress)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ShopOrder)
	for i := range nodes {
		fk := nodes[i].ShippingAddressID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(shippingaddress.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "shipping_address_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (soq *ShopOrderQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := soq.querySpec()
	if len(soq.modifiers) > 0 {
		_spec.Modifiers = soq.modifiers
	}
	_spec.Node.Columns = soq.ctx.Fields
	if len(soq.ctx.Fields) > 0 {
		_spec.Unique = soq.ctx.Unique != nil && *soq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, soq.driver, _spec)
}

func (soq *ShopOrderQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(shoporder.Table, shoporder.Columns, sqlgraph.NewFieldSpec(shoporder.FieldID, field.TypeInt))
	_spec.From = soq.sql
	if unique := soq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if soq.path != nil {
		_spec.Unique = true
	}
	if fields := soq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shoporder.FieldID)
		for i := range fields {
			if fields[i] != shoporder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if soq.withShippingAddress != nil {
			_spec.Node.AddColumnOnce(shoporder.FieldShippingAddressID)
		}
	}
	if ps := soq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := soq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := soq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := soq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (soq *ShopOrderQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(soq.driver.Dialect())
	t1 := builder.Table(shoporder.Table)
	columns := soq.ctx.Fields
	if len(columns) == 0 {
		columns = shoporder.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if soq.sql != nil {
		selector = soq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if soq.ctx.Unique != nil && *soq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range soq.predicates {
		p(selector)
	}
	for _, p := range soq.order {
		p(selector)
	}
	if offset := soq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := soq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ShopOrderGroupBy is the group-by builder for ShopOrder entities.
type ShopOrderGroupBy struct {
	selector
	build *ShopOrderQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sogb *ShopOrderGroupBy) Aggregate(fns ...AggregateFunc) *ShopOrderGroupBy {
	sogb.fns = append(sogb.fns, fns...)
	return sogb
}

// Scan applies the selector query and scans the result into the given value.
func (sogb *ShopOrderGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sogb.build.ctx, "GroupBy")
	if err := sogb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShopOrderQuery, *ShopOrderGroupBy](ctx, sogb.build, sogb, sogb.build.inters, v)
}

func (sogb *ShopOrderGroupBy) sqlScan(ctx context.Context, root *ShopOrderQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sogb.fns))
	for _, fn := range sogb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sogb.flds)+len(sogb.fns))
		for _, f := range *sogb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sogb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sogb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ShopOrderSelect is the builder for selecting fields of ShopOrder entities.
type ShopOrderSelect struct {
	*ShopOrderQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sos *ShopOrderSelect) Aggregate(fns ...AggregateFunc) *ShopOrderSelect {
	sos.fns = append(sos.fns, fns...)
	return sos
}

// Scan applies the selector query and scans the result into the given value.
func (sos *ShopOrderSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sos.ctx, "Select")
	if err := sos.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ShopOrderQuery, *ShopOrderSelect](ctx, sos.ShopOrderQuery, sos, sos.inters, v)
}

func (sos *ShopOrderSelect) sqlScan(ctx context.Context, root *ShopOrderQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sos.fns))
	for _, fn := range sos.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sos.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sos.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
